In [13]:
import numpy as np
from numpy.linalg import det
from numpy.random import randint

a = randint(-32768, 32767, size=(4,4))
print(a)

[[ 25483   6693 -30680 -24715]
 [ -7497 -15539  -6506 -12046]
 [ 24678 -18418  14208   9682]
 [ -8247  23744  -5498  12155]]


In [19]:
ans = det(a)
print(f'det(a) = {0:d}')

det(a) = 0
